# Generated by Django 4.2.7 on 2023-11-30 04:59

import autoslug.fields
import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', slugify=blog.models.custom_slugify),
        ),
    ]
